baseURL = "/"
languageCode = "en-us"
title = "YAMS - Yet Another Media Server"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Install"
    url = "/install/"
    weight = 2

[[menu.main]]
    name = "Configure"
    url = "/config/"
    weight = 3

[[menu.main]]
    name = "Advanced"
    url = "/advanced/"
    weight = 4

[[menu.main]]
    name = "FAQs"
    url = "/faqs/"
    weight = 5

[[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 6

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[[menu.main]]
    name = "Forum"
    url = "https://forum.yams.media"
    weight = 97

[[menu.main]]
    name = "Discord"
    url = "https://discord.gg/Gwae3tNMST"
    weight = 98

[[menu.main]]
    name = "Matrix"
    url = "https://matrix.to/#/#yams-space:rogs.me"
    weight = 99

# [[menu.main]]
#     name = "Gitlab"
#     url = "https://gitlab.com/rogs/yams"
#     weight = 100

[[menu.main]]
    name = "🇫🇷 FR"
    url = "https://fr.yams.media"
    weight = 100


[params]
  homepage_button_link = '/install'
  homepage_button_text = 'Learn more'
  homepage_intro = 'YAMS is a basic but powerful media server installation script'
  homepage_image = '/install-yams.gif'
  mainSections = ['install', 'config', 'faqs', 'donate', 'contact', 'advanced']

  ## You can enable to add anchor links to header elements
  enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "YAMS is a basic but powerful media server, easy to install in a bash script"
    meta_og_title = "YAMS - Yet Another Media Server"
    meta_og_type = "website"
    meta_og_url = "https://yams.media"
    meta_og_image = "/pics/logo.png"
    meta_og_description = "YAMS is a basic but powerful media server installation script"

  [params.logo]
      standard  = "/pics/logo.png"
      mobile  = "/pics/logo.png"
