baseURL = "/"
languageCode = "en-us"
title = "YAMS - Yet Another Media Server"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'YAMS is a basic but powerful media server, easy to install in a bash script'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "YAMS is a basic but powerful media server, easy to install in a bash script"
    meta_og_title = "YAMS - Yet Another Media Server"
    meta_og_type = "website"
    meta_og_url = "https://yams.media"
    meta_og_image = "/pics/logo.png"
    meta_og_description = "YAMS is a basic but powerful media server, easy to install in a bash script"
    meta_twitter_card = "summary"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/pics/logo.png"
