#!/bin/sh
#
set -eo pipefail

find ./ -type f -name '*.png' -not -path '*/.git/*' -exec sh -c 'cwebp $1 -o "${1%.png}.webp"' _ {} \;
find . -type f -not -path '*/.git/*' \( ! -iname "pre-commit" \) -exec sed -i -e 's/\.png/\.webp/g' {} \;
